/**
 * Types for mood-based audio generation API
 * Uses Genkit AI to generate audio parameters based on user mood and theme color
 */

/**
 * Puff sound parameters - soft air/breath sounds
 */
export interface PuffParams {
  /** Start time offset in seconds */
  startTime: number
  /** Duration in seconds (typically 0.04 - 0.45) */
  duration: number
  /** Frequency in Hz (typically 400 - 3500) */
  frequency: number
  /** Volume level (0.0 - 1.0, typically 0.1 - 0.35) */
  volume: number
}

/**
 * Tone sound parameters - musical tones
 */
export interface ToneParams {
  /** Start time offset in seconds */
  startTime: number
  /** Duration in seconds (typically 0.08 - 0.5) */
  duration: number
  /** Frequency in Hz (musical note, typically 262 - 1319 Hz) */
  frequency: number
  /** Volume level (0.0 - 1.0, typically 0.1 - 0.3) */
  volume: number
  /** Oscillator type */
  type: 'sine' | 'triangle' | 'square' | 'sawtooth'
  /** Optional ending frequency for pitch bends */
  frequencyEnd?: number
  /** Optional filter frequency for warm tones */
  filterFrequency?: number
}

/**
 * Complete audio sequence generated by AI
 */
export interface AudioSequence {
  /** Array of puff (breath/air) sounds */
  puffs: PuffParams[]
  /** Array of tone (musical) sounds */
  tones: ToneParams[]
  /** Overall volume modifier (0.0 - 1.0) */
  masterVolume: number
  /** Description of the emotional quality */
  emotionalDescription: string
}

/**
 * Request to generate mood-based audio
 */
export interface GenerateMoodAudioRequest {
  /** User's mood description (e.g., "I'm feeling great today!") */
  moodText: string
  /** Current theme color in hex format (e.g., "#6200ee") */
  themeColor: string
  /** Current color scheme */
  scheme: 'light' | 'dark' | 'auto'
}

/**
 * Response with generated audio parameters
 */
export interface GenerateMoodAudioResponse {
  /** Success status */
  success: boolean
  /** Generated audio sequence */
  audioSequence: AudioSequence | null
  /** Detected mood/feeling category */
  detectedMood: string
  /** Confidence level (0.0 - 1.0) */
  confidence: number
  /** Error message if failed */
  error?: string
}

/**
 * Color mood mapping - associates colors with emotional qualities
 */
export interface ColorMoodMapping {
  /** The color hex value */
  color: string
  /** Associated mood qualities */
  moods: string[]
  /** Base frequency range for this color */
  frequencyRange: {
    min: number
    max: number
  }
  /** Suggested puff characteristics */
  puffCharacter: 'soft' | 'bright' | 'warm' | 'energetic' | 'calm'
}

/**
 * Predefined color-mood associations
 */
export const COLOR_MOOD_PRESETS: ColorMoodMapping[] = [
  {
    color: '#9D8FE8', // Lavender
    moods: ['peaceful', 'calm', 'dreamy'],
    frequencyRange: { min: 350, max: 550 },
    puffCharacter: 'soft'
  },
  {
    color: '#F48B9D', // Rose
    moods: ['loving', 'warm', 'gentle'],
    frequencyRange: { min: 400, max: 600 },
    puffCharacter: 'warm'
  },
  {
    color: '#7ED997', // Mint
    moods: ['refreshed', 'hopeful', 'renewed'],
    frequencyRange: { min: 500, max: 700 },
    puffCharacter: 'bright'
  },
  {
    color: '#FFC875', // Amber
    moods: ['joyful', 'optimistic', 'sunny'],
    frequencyRange: { min: 600, max: 900 },
    puffCharacter: 'warm'
  },
  {
    color: '#6DD5FA', // Sky
    moods: ['free', 'open', 'serene'],
    frequencyRange: { min: 450, max: 650 },
    puffCharacter: 'soft'
  },
  {
    color: '#FF9E7C', // Coral
    moods: ['energetic', 'playful', 'vibrant'],
    frequencyRange: { min: 700, max: 1000 },
    puffCharacter: 'energetic'
  },
  {
    color: '#7380E8', // Indigo
    moods: ['deep', 'thoughtful', 'focused'],
    frequencyRange: { min: 300, max: 500 },
    puffCharacter: 'calm'
  },
  {
    color: '#FF79A8', // Blush
    moods: ['excited', 'happy', 'affectionate'],
    frequencyRange: { min: 650, max: 900 },
    puffCharacter: 'bright'
  },
  {
    color: '#64E0F0', // Aqua
    moods: ['refreshing', 'clarity', 'light'],
    frequencyRange: { min: 550, max: 800 },
    puffCharacter: 'bright'
  },
  {
    color: '#FFE066', // Gold
    moods: ['triumphant', 'confident', 'radiant'],
    frequencyRange: { min: 700, max: 1100 },
    puffCharacter: 'energetic'
  },
  {
    color: '#6B7E91', // Slate
    moods: ['grounded', 'stable', 'neutral'],
    frequencyRange: { min: 300, max: 450 },
    puffCharacter: 'calm'
  },
  {
    color: '#3D4451', // Onyx
    moods: ['mysterious', 'deep', 'contemplative'],
    frequencyRange: { min: 250, max: 400 },
    puffCharacter: 'soft'
  },
  {
    color: '#8E6BA8', // Plum
    moods: ['luxurious', 'creative', 'rich'],
    frequencyRange: { min: 400, max: 600 },
    puffCharacter: 'warm'
  },
  {
    color: '#5A7A5F', // Forest
    moods: ['grounded', 'natural', 'peaceful'],
    frequencyRange: { min: 350, max: 500 },
    puffCharacter: 'calm'
  },
  {
    color: '#3D5A80', // Navy
    moods: ['trustworthy', 'calm', 'professional'],
    frequencyRange: { min: 300, max: 450 },
    puffCharacter: 'calm'
  },
  {
    color: '#994F5E', // Burgundy
    moods: ['sophisticated', 'warm', 'intense'],
    frequencyRange: { min: 350, max: 550 },
    puffCharacter: 'warm'
  }
]
