/**
 * Types for mood-based audio generation
 * Local copy for Schmancy package to avoid external dependency
 */
/**
 * Puff sound parameters - soft air/breath sounds
 */
export interface PuffParams {
    /** Start time offset in seconds */
    startTime: number;
    /** Duration in seconds (typically 0.04 - 0.45) */
    duration: number;
    /** Frequency in Hz (typically 400 - 3500) */
    frequency: number;
    /** Volume level (0.0 - 1.0, typically 0.1 - 0.35) */
    volume: number;
}
/**
 * Tone sound parameters - musical tones
 */
export interface ToneParams {
    /** Start time offset in seconds */
    startTime: number;
    /** Duration in seconds (typically 0.08 - 0.5) */
    duration: number;
    /** Frequency in Hz (musical note, typically 262 - 1319 Hz) */
    frequency: number;
    /** Volume level (0.0 - 1.0, typically 0.1 - 0.3) */
    volume: number;
    /** Oscillator type */
    type: 'sine' | 'triangle' | 'square' | 'sawtooth';
    /** Optional ending frequency for pitch bends */
    frequencyEnd?: number;
    /** Optional filter frequency for warm tones */
    filterFrequency?: number;
}
/**
 * Complete audio sequence generated by AI
 */
export interface AudioSequence {
    /** Array of puff (breath/air) sounds */
    puffs: PuffParams[];
    /** Array of tone (musical) sounds */
    tones: ToneParams[];
    /** Overall volume modifier (0.0 - 1.0) */
    masterVolume: number;
    /** Description of the emotional quality */
    emotionalDescription: string;
}
/**
 * Request to generate mood audio
 */
export interface GenerateMoodAudioRequest {
    /** User's description of their mood */
    moodText: string;
    /** Current theme color in hex format */
    themeColor: string;
    /** Current color scheme */
    scheme: 'dark' | 'light' | 'auto';
}
/**
 * Response from mood audio generation
 */
export interface GenerateMoodAudioResponse {
    /** Whether generation was successful */
    success: boolean;
    /** Generated audio sequence (null if failed) */
    audioSequence: AudioSequence | null;
    /** Detected mood from the text */
    detectedMood: string;
    /** Confidence level (0-1) */
    confidence: number;
    /** Error message if failed */
    error?: string;
}
/** Feeling category names */
export type FeelingCategory = 'happy' | 'sad' | 'anxious' | 'angry' | 'tired' | 'calm' | 'connected' | 'mixed';
/** Happy / Pleasant feelings */
export type HappyFeeling = 'joyful' | 'content' | 'excited' | 'proud' | 'hopeful' | 'relieved' | 'grateful' | 'peaceful' | 'playful' | 'amused' | 'curious' | 'inspired' | 'confident' | 'loved' | 'comforted' | 'energized' | 'celebrated';
/** Sad / Low feelings */
export type SadFeeling = 'sad' | 'lonely' | 'disappointed' | 'heartbroken' | 'grieving' | 'hopeless' | 'empty' | 'discouraged' | 'melancholic' | 'homesick' | 'hurt' | 'miserable' | 'regretful' | 'ashamed' | 'inferior';
/** Anxious / Fearful feelings */
export type AnxiousFeeling = 'anxious' | 'worried' | 'afraid' | 'terrified' | 'panicked' | 'nervous' | 'uneasy' | 'insecure' | 'overwhelmed' | 'stressed' | 'tense' | 'apprehensive' | 'startled' | 'suspicious' | 'vulnerable';
/** Angry / Frustrated feelings */
export type AngryFeeling = 'annoyed' | 'irritated' | 'frustrated' | 'angry' | 'enraged' | 'bitter' | 'resentful' | 'jealous' | 'envious' | 'indignant' | 'impatient' | 'hostile' | 'contemptuous';
/** Tired / Drained feelings */
export type TiredFeeling = 'tired' | 'exhausted' | 'drained' | 'burnedOut' | 'numb' | 'bored' | 'unmotivated' | 'apathetic' | 'restless';
/** Calm / Grounded feelings */
export type CalmFeeling = 'calm' | 'relaxed' | 'atEase' | 'balanced' | 'stable' | 'secure' | 'safe' | 'centered' | 'grounded' | 'accepting';
/** Connected / Social feelings */
export type ConnectedFeeling = 'connected' | 'accepted' | 'included' | 'belonging' | 'appreciated' | 'valued' | 'respected' | 'supported' | 'protective' | 'compassionate' | 'empathetic';
/** Mixed / Complicated feelings */
export type MixedFeeling = 'conflicted' | 'confused' | 'ambivalent' | 'nostalgic' | 'guilty' | 'embarrassed' | 'surprised' | 'shocked' | 'awestruck' | 'skeptical';
/** All feeling types */
export type Feeling = HappyFeeling | SadFeeling | AnxiousFeeling | AngryFeeling | TiredFeeling | CalmFeeling | ConnectedFeeling | MixedFeeling;
/**
 * Sound definition for a single feeling
 * Contains the puffs and tones that make up the emotional sound
 */
export interface FeelingSound {
    /** Puff sounds (breath/air) for this feeling */
    puffs: PuffParams[];
    /** Tone sounds (musical) for this feeling */
    tones: ToneParams[];
    /** Optional description of the sound character */
    description?: string;
}
/**
 * Complete Sound Theme - like a color palette but for sounds
 * Defines how each emotion sounds
 */
export interface SoundTheme {
    /** Theme identifier */
    name: string;
    /** Human-readable description */
    description: string;
    /** Master volume modifier (0.0 - 1.0) */
    masterVolume: number;
    /** Sound definitions for each feeling - partial allows overriding specific feelings */
    feelings: Partial<Record<Feeling, FeelingSound>>;
    /** Category-level defaults - used when specific feeling not defined */
    categoryDefaults?: Partial<Record<FeelingCategory, FeelingSound>>;
    /** Metadata about the theme origin */
    metadata?: {
        /** Source color that inspired this theme */
        sourceColor?: string;
        /** Source mood text */
        sourceMood?: string;
        /** Color scheme when generated */
        scheme?: 'dark' | 'light' | 'auto';
        /** When the theme was generated */
        generatedAt?: string;
        /** AI model that generated it */
        generatedBy?: string;
    };
}
/**
 * Sound theme settings stored in context
 */
export interface SoundThemeSettings {
    /** Current active sound theme (null = use defaults) */
    theme: SoundTheme | null;
    /** Global volume (0.0 - 1.0) */
    volume: number;
    /** Whether sounds are muted */
    muted: boolean;
}
/**
 * Request to generate a sound theme from AI
 */
export interface GenerateSoundThemeRequest {
    /** User's mood description */
    moodText: string;
    /** Theme color in hex */
    themeColor: string;
    /** Color scheme */
    scheme: 'dark' | 'light' | 'auto';
    /** Which feelings to generate sounds for (optional - default all) */
    feelings?: Feeling[];
    /** Which categories to prioritize */
    priorityCategories?: FeelingCategory[];
}
/**
 * Response from sound theme generation
 */
export interface GenerateSoundThemeResponse {
    /** Whether generation succeeded */
    success: boolean;
    /** Generated sound theme */
    theme: SoundTheme | null;
    /** Error message if failed */
    error?: string;
}
